# Project Yield - Data Exploration & Ratio Testing

This notebook provides interactive examples for:
1. Loading parquet data (prices, quarterly & annual fundamentals)
2. Computing all ratios for a single stock via `RatioCalculator.get_all_ratios`
3. Batch ratio computation via `MetricsEngine.calculate_all_ratios`

## 1. Setup

In [1]:
import sys
from pathlib import Path

# Ensure the project root is on the path so imports work
project_root = Path.cwd().parent
if str(project_root / "src") not in sys.path:
    sys.path.insert(0, str(project_root / "src"))

import polars as pl
from project_yield.config import Settings
from project_yield.data.reader import DataReader
from project_yield.analysis.ratios import RatioCalculator
from project_yield.analysis.metrics import MetricsEngine

# Initialize with data_path pointing to the project data directory
settings = Settings(data_path=project_root / "data")
reader = DataReader(settings)

print(f"Data path: {settings.data_path}")
print(f"Available price tickers: {reader.list_tickers('prices')[:10]} ...")
print(f"Available quarterly tickers: {reader.list_tickers('quarterly')[:10]} ...")

Data path: /home/singkwan/project_yield/data
Available price tickers: ['AAPL', 'ABBV', 'ABT', 'ACN', 'ADBE', 'AMD', 'AMGN', 'AMZN', 'AVGO', 'CMCSA'] ...
Available quarterly tickers: ['ABBV', 'ABT', 'ACN', 'ADBE', 'AMD', 'AMGN', 'AMZN', 'AVGO', 'CMCSA', 'CRM'] ...

'2020-01-01'

## 2. Load Price Data

In [4]:
TICKER = "GRAB"  # Change this to test other stocks

# Load all price data for a single ticker (lazy -> collect)
prices_df = reader.get_prices(ticker=TICKER).collect()
print(f"{TICKER} price rows: {len(prices_df)}")
print(f"Date range: {prices_df['date'].min()} to {prices_df['date'].max()}")
print(f"Columns: {prices_df.columns}\n")
prices_df.head(10)

GRAB price rows: 0
Date range: None to None
Columns: ['ticker', 'date', 'SimFinId', 'open', 'high', 'low', 'close', 'adjusted_close', 'volume', 'Dividend', 'Shares Outstanding', 'year']

shape: (0, 12)
┌────────┬──────────────┬──────────┬──────┬───┬────────┬──────────┬────────────────────┬──────┐
│ ticker ┆ date         ┆ SimFinId ┆ open ┆ … ┆ volume ┆ Dividend ┆ Shares Outstanding ┆ year │
│ ---    ┆ ---          ┆ ---      ┆ ---  ┆   ┆ ---    ┆ ---      ┆ ---                ┆ ---  │
│ str    ┆ datetime[ns] ┆ i64      ┆ f64  ┆   ┆ i64    ┆ f64      ┆ f64                ┆ i32  │
╞════════╪══════════════╪══════════╪══════╪═══╪════════╪══════════╪════════════════════╪══════╡
└────────┴──────────────┴──────────┴──────┴───┴────────┴──────────┴────────────────────┴──────┘

In [3]:
# Latest price
latest = reader.get_latest_price(TICKER)
print(f"Latest price for {TICKER}:")
latest

Latest price for MSFT:

shape: (1, 12)
┌────────┬──────────────┬──────────┬───────┬───┬──────────┬──────────┬──────────────────────┬──────┐
│ ticker ┆ date         ┆ SimFinId ┆ open  ┆ … ┆ volume   ┆ Dividend ┆ Shares Outstanding   ┆ year │
│ ---    ┆ ---          ┆ ---      ┆ ---   ┆   ┆ ---      ┆ ---      ┆ ---                  ┆ ---  │
│ str    ┆ datetime[ns] ┆ i64      ┆ f64   ┆   ┆ i64      ┆ f64      ┆ f64                  ┆ i32  │
╞════════╪══════════════╪══════════╪═══════╪═══╪══════════╪══════════╪══════════════════════╪══════╡
│ MSFT   ┆ 2025-02-06   ┆ 59265    ┆ 414.0 ┆ … ┆ 16309755 ┆ null     ┆ 7.4340e9             ┆ 2025 │
│        ┆ 00:00:00     ┆          ┆       ┆   ┆          ┆          ┆                      ┆      │
└────────┴──────────────┴──────────┴───────┴───┴──────────┴──────────┴──────────────────────┴──────┘

In [13]:
# Filter by date range
from datetime import date

prices_2024 = reader.get_prices(
    ticker=TICKER,
    start_date=date(2025, 1, 1),
    end_date=date(2025, 12, 31),
).collect()

print(f"{TICKER} 2024 price rows: {len(prices_2024)}")
prices_2024.tail(10)

MSFT 2024 price rows: 24

shape: (10, 12)
┌────────┬──────────────┬──────────┬────────┬───┬──────────┬──────────┬─────────────────────┬──────┐
│ ticker ┆ date         ┆ SimFinId ┆ open   ┆ … ┆ volume   ┆ Dividend ┆ Shares Outstanding  ┆ year │
│ ---    ┆ ---          ┆ ---      ┆ ---    ┆   ┆ ---      ┆ ---      ┆ ---                 ┆ ---  │
│ str    ┆ datetime[ns] ┆ i64      ┆ f64    ┆   ┆ i64      ┆ f64      ┆ f64                 ┆ i32  │
╞════════╪══════════════╪══════════╪════════╪═══╪══════════╪══════════╪═════════════════════╪══════╡
│ MSFT   ┆ 2025-01-24   ┆ 59265    ┆ 445.16 ┆ … ┆ 15549453 ┆ null     ┆ 7.4340e9            ┆ 2025 │
│        ┆ 00:00:00     ┆          ┆        ┆   ┆          ┆          ┆                     ┆      │
│ MSFT   ┆ 2025-01-27   ┆ 59265    ┆ 424.01 ┆ … ┆ 35647805 ┆ null     ┆ 7.4340e9            ┆ 2025 │
│        ┆ 00:00:00     ┆          ┆        ┆   ┆          ┆          ┆                     ┆      │
│ MSFT   ┆ 2025-01-28   ┆ 59265    ┆ 434.6  ┆ … ┆ 23491703 ┆ null     ┆ 7.4340e9            ┆ 2025 │
│        ┆ 00:00:00     ┆          ┆        ┆   ┆          ┆          ┆                     ┆      │
│ MSFT   ┆ 2025-01-29   ┆ 59265    ┆ 446.69 ┆ … ┆ 23581370 ┆ null     ┆ 7.4340e9            ┆ 2025 │
│        ┆ 00:00:00     ┆          ┆        ┆   ┆          ┆          ┆                     ┆      │
│ MSFT   ┆ 2025-01-30   ┆ 59265    ┆ 418.77 ┆ … ┆ 54586260 ┆ null     ┆ 7.4340e9            ┆ 2025 │
│        ┆ 00:00:00     ┆          ┆        ┆   ┆          ┆          ┆                     ┆      │
│ MSFT   ┆ 2025-01-31   ┆ 59265    ┆ 418.98 ┆ … ┆ 34223388 ┆ null     ┆ 7.4340e9            ┆ 2025 │
│        ┆ 00:00:00     ┆          ┆        ┆   ┆          ┆          ┆                     ┆      │
│ MSFT   ┆ 2025-02-03   ┆ 59265    ┆ 411.6  ┆ … ┆ 25679149 ┆ null     ┆ 7.4340e9            ┆ 2025 │
│        ┆ 00:00:00     ┆          ┆        ┆   ┆          ┆          ┆                     ┆      │
│ MSFT   ┆ 2025-02-04   ┆ 59265    ┆ 412.69 ┆ … ┆ 20532096 ┆ null     ┆ 7.4340e9            ┆ 2025 │
│        ┆ 00:00:00     ┆          ┆        ┆   ┆          ┆          ┆                     ┆      │
│ MSFT   ┆ 2025-02-05   ┆ 59265    ┆ 412.35 ┆ … ┆ 16336188 ┆ null     ┆ 7.4340e9            ┆ 2025 │
│        ┆ 00:00:00     ┆          ┆        ┆   ┆          ┆          ┆                     ┆      │
│ MSFT   ┆ 2025-02-06   ┆ 59265    ┆ 414.0  ┆ … ┆ 16309755 ┆ null     ┆ 7.4340e9            ┆ 2025 │
│        ┆ 00:00:00     ┆          ┆        ┆   ┆          ┆          ┆                     ┆      │
└────────┴──────────────┴──────────┴────────┴───┴──────────┴──────────┴─────────────────────┴──────┘

## 3. Load Fundamentals Data

In [6]:
# Quarterly fundamentals
quarterly_df = reader.get_fundamentals_quarterly(ticker=TICKER).collect()
print(f"{TICKER} quarterly rows: {len(quarterly_df)}")
print(f"Columns ({len(quarterly_df.columns)}): {quarterly_df.columns}\n")
quarterly_df.sort("Publish Date", descending=True).head(8)

MSFT quarterly rows: 20
Columns (67): ['ticker', 'report_date', 'company_id', 'Currency', 'fiscal_year', 'fiscal_period', 'Publish Date', 'Restated Date', 'Shares (Basic)', 'Shares (Diluted)', 'revenue', 'Cost of Revenue', 'gross_profit', 'Operating Expenses', 'Selling, General & Administrative', 'rd_expense', 'Depreciation & Amortization', 'operating_income', 'Non-Operating Income (Loss)', 'Interest Expense, Net', 'Pretax Income (Loss), Adj.', 'Abnormal Gains (Losses)', 'Pretax Income (Loss)', 'Income Tax (Expense) Benefit, Net', 'Income (Loss) from Continuing Operations', 'Net Extraordinary Gains (Losses)', 'net_income', 'Net Income (Common)', 'shares_outstanding', 'Cash, Cash Equivalents & Short Term Investments', 'Accounts & Notes Receivable', 'Inventories', 'Total Current Assets', 'Property, Plant & Equipment, Net', 'Long Term Investments & Receivables', 'Other Long Term Assets', 'Total Noncurrent Assets', 'total_assets', 'Payables & Accruals', 'Short Term Debt', 'Total Current Liabilities', 'Long Term Debt', 'Total Noncurrent Liabilities', 'total_liabilities', 'Share Capital & Additional Paid-In Capital', 'Treasury Stock', 'Retained Earnings', 'shareholders_equity', 'Total Liabilities & Equity', 'Net Income/Starting Line', 'Non-Cash Items', 'Change in Working Capital', 'Change in Accounts Receivable', 'Change in Inventories', 'Change in Accounts Payable', 'Change in Other', 'operating_cash_flow', 'capex', 'Net Change in Long Term Investment', 'Net Cash from Acquisitions & Divestitures', 'investing_cash_flow', 'Dividends Paid', 'Cash from (Repayment of) Debt', 'Cash from (Repurchase of) Equity', 'financing_cash_flow', 'Net Change in Cash', 'free_cash_flow']

shape: (8, 67)
┌────────┬────────────┬────────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ ticker ┆ report_dat ┆ company_id ┆ Currency ┆ … ┆ Cash from  ┆ financing ┆ Net       ┆ free_cash │
│ ---    ┆ e          ┆ ---        ┆ ---      ┆   ┆ (Repurchas ┆ _cash_flo ┆ Change in ┆ _flow     │
│ str    ┆ ---        ┆ i64        ┆ str      ┆   ┆ e of)      ┆ w         ┆ Cash      ┆ ---       │
│        ┆ datetime[n ┆            ┆          ┆   ┆ Equi…      ┆ ---       ┆ ---       ┆ f64       │
│        ┆ s]         ┆            ┆          ┆   ┆ ---        ┆ f64       ┆ i64       ┆           │
│        ┆            ┆            ┆          ┆   ┆ f64        ┆           ┆           ┆           │
╞════════╪════════════╪════════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ MSFT   ┆ 2024-12-31 ┆ 59265      ┆ USD      ┆ … ┆ -4.7300e9  ┆ -1.0900e1 ┆ -33580000 ┆ 6.4870e9  │
│        ┆ 00:00:00   ┆            ┆          ┆   ┆            ┆ 0         ┆ 00        ┆           │
│ MSFT   ┆ 2024-09-30 ┆ 59265      ┆ USD      ┆ … ┆ -3.4010e9  ┆ -1.5687e1 ┆ 252500000 ┆ 1.9257e10 │
│        ┆ 00:00:00   ┆            ┆          ┆   ┆            ┆ 0         ┆ 0         ┆           │
│ MSFT   ┆ 2024-06-30 ┆ 59265      ┆ USD      ┆ … ┆ -3.6760e9  ┆ -2.3642e1 ┆ -13190000 ┆ 2.3322e10 │
│        ┆ 00:00:00   ┆            ┆          ┆   ┆            ┆ 0         ┆ 00        ┆           │
│ MSFT   ┆ 2024-03-31 ┆ 59265      ┆ USD      ┆ … ┆ -3.6910e9  ┆ -1.9591e1 ┆ 232900000 ┆ 2.0965e10 │
│        ┆ 00:00:00   ┆            ┆          ┆   ┆            ┆ 0         ┆ 0         ┆           │
│ MSFT   ┆ 2023-12-31 ┆ 59265      ┆ USD      ┆ … ┆ -3.7390e9  ┆ -8.5990e9 ┆ -63147000 ┆ 9.1180e9  │
│        ┆ 00:00:00   ┆            ┆          ┆   ┆            ┆           ┆ 000       ┆           │
│ MSFT   ┆ 2023-09-30 ┆ 59265      ┆ USD      ┆ … ┆ -4.1460e9  ┆ 1.4086e10 ┆ 457480000 ┆ 2.0666e10 │
│        ┆ 00:00:00   ┆            ┆          ┆   ┆            ┆           ┆ 00        ┆           │
│ MSFT   ┆ 2023-06-30 ┆ 59265      ┆ USD      ┆ … ┆ -5.1920e9  ┆ -1.1515e1 ┆ 814200000 ┆ 1.9827e10 │
│        ┆ 00:00:00   ┆            ┆          ┆   ┆            ┆ 0         ┆ 0         ┆           │
│ MSFT   ┆ 2023-03-31 ┆ 59265      ┆ USD      ┆ … ┆ -4.9730e9  ┆ -1.1718e1 ┆ 109160000 ┆ 1.7834e10 │
│        ┆ 00:00:00   ┆            ┆          ┆   ┆            ┆ 0         ┆ 00        ┆           │
└────────┴────────────┴────────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [7]:
# Annual fundamentals
annual_df = reader.get_fundamentals_annual(ticker=TICKER).collect()
print(f"{TICKER} annual rows: {len(annual_df)}")
annual_df.sort("fiscal_period", descending=True).head()

MSFT annual rows: 20

shape: (5, 67)
┌────────┬────────────┬────────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ ticker ┆ report_dat ┆ company_id ┆ Currency ┆ … ┆ Cash from  ┆ financing ┆ Net       ┆ free_cash │
│ ---    ┆ e          ┆ ---        ┆ ---      ┆   ┆ (Repurchas ┆ _cash_flo ┆ Change in ┆ _flow     │
│ str    ┆ ---        ┆ i64        ┆ str      ┆   ┆ e of)      ┆ w         ┆ Cash      ┆ ---       │
│        ┆ datetime[n ┆            ┆          ┆   ┆ Equi…      ┆ ---       ┆ ---       ┆ f64       │
│        ┆ s]         ┆            ┆          ┆   ┆ ---        ┆ f64       ┆ i64       ┆           │
│        ┆            ┆            ┆          ┆   ┆ f64        ┆           ┆           ┆           │
╞════════╪════════════╪════════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ MSFT   ┆ 2020-06-30 ┆ 59265      ┆ USD      ┆ … ┆ -5.4510e9  ┆ -1.0557e1 ┆ 186600000 ┆ 1.0512e10 │
│        ┆ 00:00:00   ┆            ┆          ┆   ┆            ┆ 0         ┆ 0         ┆           │
│ MSFT   ┆ 2021-06-30 ┆ 59265      ┆ USD      ┆ … ┆ -6.7270e9  ┆ -9.7700e9 ┆ 522000000 ┆ 1.4504e10 │
│        ┆ 00:00:00   ┆            ┆          ┆   ┆            ┆           ┆           ┆           │
│ MSFT   ┆ 2022-06-30 ┆ 59265      ┆ USD      ┆ … ┆ -8.2960e9  ┆ -1.4066e1 ┆ 143300000 ┆ 1.7758e10 │
│        ┆ 00:00:00   ┆            ┆          ┆   ┆            ┆ 0         ┆ 0         ┆           │
│ MSFT   ┆ 2023-06-30 ┆ 59265      ┆ USD      ┆ … ┆ -5.1920e9  ┆ -1.1515e1 ┆ 814200000 ┆ 1.9827e10 │
│        ┆ 00:00:00   ┆            ┆          ┆   ┆            ┆ 0         ┆ 0         ┆           │
│ MSFT   ┆ 2024-06-30 ┆ 59265      ┆ USD      ┆ … ┆ -3.6760e9  ┆ -2.3642e1 ┆ -13190000 ┆ 2.3322e10 │
│        ┆ 00:00:00   ┆            ┆          ┆   ┆            ┆ 0         ┆ 00        ┆           │
└────────┴────────────┴────────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [8]:
# TTM (Trailing Twelve Months) fundamentals
ttm_df = reader.get_ttm_fundamentals(TICKER)
print(f"{TICKER} TTM fundamentals:")
ttm_df

MSFT TTM fundamentals:

shape: (1, 62)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ company_id ┆ Shares     ┆ Shares    ┆ revenue   ┆ … ┆ Net       ┆ free_cash ┆ ticker ┆ quarters_ │
│ ---        ┆ (Basic)    ┆ (Diluted) ┆ ---       ┆   ┆ Change in ┆ _flow     ┆ ---    ┆ included  │
│ i64        ┆ ---        ┆ ---       ┆ f64       ┆   ┆ Cash      ┆ ---       ┆ str    ┆ ---       │
│            ┆ f64        ┆ f64       ┆           ┆   ┆ ---       ┆ f64       ┆        ┆ i64       │
│            ┆            ┆           ┆           ┆   ┆ i64       ┆           ┆        ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ 237060     ┆ 3.0068e10  ┆ 3.0279e10 ┆ 1.9224e11 ┆ … ┆ 119630000 ┆ 6.2601e10 ┆ MSFT   ┆ 4         │
│            ┆            ┆           ┆           ┆   ┆ 00        ┆           ┆        ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

In [9]:
# Select specific columns to inspect key financials
key_cols = ["fiscal_period", "revenue", "gross_profit", "operating_income",
            "net_income", "rd_expense", "shares_outstanding", "free_cash_flow"]
available = [c for c in key_cols if c in quarterly_df.columns]

quarterly_df.select(available).sort("fiscal_period", descending=True).head(8)

shape: (8, 8)
┌────────────┬───────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ fiscal_per ┆ revenue   ┆ gross_prof ┆ operating_ ┆ net_incom ┆ rd_expens ┆ shares_ou ┆ free_cash │
│ iod        ┆ ---       ┆ it         ┆ income     ┆ e         ┆ e         ┆ tstanding ┆ _flow     │
│ ---        ┆ f64       ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆           ┆ f64        ┆ f64        ┆ i64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Q4         ┆ 3.8033e10 ┆ 2.5694e10  ┆ 1.3407e10  ┆ 112020000 ┆ -5.2140e9 ┆ 7.6560e9  ┆ 1.0512e10 │
│            ┆           ┆            ┆            ┆ 00        ┆           ┆           ┆           │
│ Q4         ┆ 4.6152e10 ┆ 3.2161e10  ┆ 1.9095e10  ┆ 164580000 ┆ -5.6870e9 ┆ 7.6170e9  ┆ 1.4504e10 │
│            ┆           ┆            ┆            ┆ 00        ┆           ┆           ┆           │
│ Q4         ┆ 5.1865e10 ┆ 3.5436e10  ┆ 2.0534e10  ┆ 167400000 ┆ -6.8490e9 ┆ 7.5400e9  ┆ 1.7758e10 │
│            ┆           ┆            ┆            ┆ 00        ┆           ┆           ┆           │
│ Q4         ┆ 5.6189e10 ┆ 3.9394e10  ┆ 2.4254e10  ┆ 200810000 ┆ -6.7390e9 ┆ 7.4660e9  ┆ 1.9827e10 │
│            ┆           ┆            ┆            ┆ 00        ┆           ┆           ┆           │
│ Q4         ┆ 6.4727e10 ┆ 4.5043e10  ┆ 2.7925e10  ┆ 220360000 ┆ -8.0560e9 ┆ 7.4740e9  ┆ 2.3322e10 │
│            ┆           ┆            ┆            ┆ 00        ┆           ┆           ┆           │
│ Q3         ┆ 3.5021e10 ┆ 2.4046e10  ┆ 1.2975e10  ┆ 107520000 ┆ -4.8870e9 ┆ 7.6750e9  ┆ 1.3737e10 │
│            ┆           ┆            ┆            ┆ 00        ┆           ┆           ┆           │
│ Q3         ┆ 4.1706e10 ┆ 2.8661e10  ┆ 1.7048e10  ┆ 154570000 ┆ -5.2040e9 ┆ 7.5970e9  ┆ 1.7090e10 │
│            ┆           ┆            ┆            ┆ 00        ┆           ┆           ┆           │
│ Q3         ┆ 4.9360e10 ┆ 3.3745e10  ┆ 2.0364e10  ┆ 167280000 ┆ -6.3060e9 ┆ 7.5550e9  ┆ 2.0046e10 │
│            ┆           ┆            ┆            ┆ 00        ┆           ┆           ┆           │
└────────────┴───────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

## 4. RatioCalculator - `get_all_ratios` for a Single Stock

In [10]:
calc = RatioCalculator(settings)

ratios = calc.get_all_ratios(TICKER)
print(f"All ratios for {TICKER}:")
for key, value in ratios.items():
    print(f"  {key:20s}: {value}")

2026-03-01 00:01:26.362 | WARNING  | project_yield.analysis.ratios:get_peg_ratio:121 - MSFT: Cannot calculate PEG - negative or zero growth

All ratios for MSFT:
  ticker              : MSFT
  as_of_date          : latest
  pe_ratio            : 195.26
  peg_ratio           : None
  operating_margin    : 0.4021
  net_profit_margin   : 0.3354
  gross_margin        : 0.6902
  revenue_growth      : -0.4124
  eps_growth          : -0.5037
  rd_intensity        : 0.1274
  capex_ratio         : 0.1405

In [11]:
# View as a single-row DataFrame for easy comparison
ratios_df = pl.DataFrame([ratios])
ratios_df

shape: (1, 11)
┌────────┬────────────┬──────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ ticker ┆ as_of_date ┆ pe_ratio ┆ peg_ratio ┆ … ┆ revenue_gr ┆ eps_growth ┆ rd_intens ┆ capex_rat │
│ ---    ┆ ---        ┆ ---      ┆ ---       ┆   ┆ owth       ┆ ---        ┆ ity       ┆ io        │
│ str    ┆ str        ┆ f64      ┆ null      ┆   ┆ ---        ┆ f64        ┆ ---       ┆ ---       │
│        ┆            ┆          ┆           ┆   ┆ f64        ┆            ┆ f64       ┆ f64       │
╞════════╪════════════╪══════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ MSFT   ┆ latest     ┆ 195.26   ┆ null      ┆ … ┆ -0.4124    ┆ -0.5037    ┆ 0.1274    ┆ 0.1405    │
└────────┴────────────┴──────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [12]:
# You can also call individual ratios
pe = calc.get_pe_ratio(TICKER)
margin = calc.get_operating_margin(TICKER)
print(f"{TICKER} PE Ratio:         {pe}")
print(f"{TICKER} Operating Margin:  {margin}")

MSFT PE Ratio:         195.26
MSFT Operating Margin:  0.4021

## 5. MetricsEngine - `calculate_all_ratios` for Multiple Stocks

In [ ]:
engine = MetricsEngine(settings)

# Calculate ratios for a small batch of tickers
tickers = ["AAPL", "MSFT", "GOOG", "NVDA", "AMZN"]
all_ratios_df = engine.calculate_all_ratios(tickers)

print(f"Batch ratios shape: {all_ratios_df.shape}")
all_ratios_df

In [ ]:
# Compare specific metrics across tickers
comparison = engine.compare_tickers(
    tickers,
    metrics=["pe_ratio", "operating_margin", "revenue_growth"],
)
comparison

In [ ]:
# Rank by a metric
ranked = engine.rank_by_metric("pe_ratio", tickers=tickers, ascending=True)
print("Ranked by PE ratio (lowest first):")
ranked

In [ ]:
# Valuation summary for a single ticker
summary = engine.get_valuation_summary(TICKER)
print(f"Valuation summary for {TICKER}:")
for key, value in summary.items():
    print(f"  {key:20s}: {value}")

## 6. Visualize DataFrames

In [ ]:
import plotly.express as px

# Price history chart
prices_pd = prices_df.sort("date").to_pandas()
fig = px.line(prices_pd, x="date", y="close", title=f"{TICKER} Closing Price")
fig.show()

In [ ]:
# Quarterly revenue trend
rev_df = quarterly_df.select(["fiscal_period", "revenue"]).sort("fiscal_period").to_pandas()
fig = px.bar(rev_df, x="fiscal_period", y="revenue", title=f"{TICKER} Quarterly Revenue")
fig.show()

In [ ]:
# Compare ratios across tickers as a grouped bar chart
metrics_to_plot = ["operating_margin", "net_profit_margin", "gross_margin"]
plot_df = all_ratios_df.select(["ticker"] + metrics_to_plot)
plot_pd = plot_df.to_pandas().melt(id_vars="ticker", var_name="metric", value_name="value")

fig = px.bar(
    plot_pd,
    x="ticker",
    y="value",
    color="metric",
    barmode="group",
    title="Margin Comparison Across Tickers",
)
fig.show()

In [ ]:
# PE ratio comparison
pe_df = all_ratios_df.select(["ticker", "pe_ratio"]).drop_nulls().to_pandas()
fig = px.bar(pe_df, x="ticker", y="pe_ratio", title="PE Ratio Comparison", text_auto=".1f")
fig.show()